
import { Items } from "../../models/item.js";

export const createItem = async (req, res) => {

  console.log(req.body);
  
 


    const itemRes = await Items.insertMany(
    //   { "itemValue": "Abies nigra" },
    //   { "itemValue": "Abrus precatorius — jequirity" },
    //   { "itemValue": "Abrotanum" },
    //   { "itemValue": "Absinthium" },
    //   { "itemValue": "Acalypha indica" },
    //   { "itemValue": "Aceticum acidum" },
    //   { "itemValue": "Acetanilidum" },
    //   { "itemValue": "Aconitum napellus" },
    //   { "itemValue": "Actaea spicata" },
    //   { "itemValue": "Adonis vernalis" },
    //   { "itemValue": "Adrenalinum bitartaricum" },
    //   { "itemValue": "Aesculus hippocastanum" },
    //   { "itemValue": "Aethiops mineralis" },
    //   { "itemValue": "Aethusa cynapium" },
    //   { "itemValue": "Agaricus muscarius" },
    //   { "itemValue": "Agave americana" },
    //   { "itemValue": "Agnus castus" },
    //   { "itemValue": "Agraphis nutans" },
    //   { "itemValue": "Ailanthus glandulosa" },
    //   { "itemValue": "Aletris farinosa" },
    //   { "itemValue": "Alfalfa" },
    //   { "itemValue": "Allium cepa" },
    //   { "itemValue": "Allium sativum" },
    //   { "itemValue": "Alnus" },
    //   { "itemValue": "Alstonia scholaris" },
    //   { "itemValue": "Aloe socotrina" },
    //   { "itemValue": "Alumina" },
    //   { "itemValue": "Alumina silicata" },
    //   { "itemValue": "Alumen" },
    //   { "itemValue": "Ammonium benzoicum" },
    //   { "itemValue": "Ammonium bromatum" },
    //   { "itemValue": "Ammonium carbonicum" },
    //   { "itemValue": "Ammonium causticum" },
    //   { "itemValue": "Ammonium iodatum" },
    //   { "itemValue": "Ammonium muriaticum" },
    //   { "itemValue": "Ammonium phosphoricum" },
    //   { "itemValue": "Ammonium picricum" },
    //   { "itemValue": "Ammonium valerianicum" },
    //   { "itemValue": "Ambra grisea" },
    //   { "itemValue": "Ambrosia artemisiaefolia" },
    //   { "itemValue": "Amygdalus persica" },
    //   { "itemValue": "Amylenum nitrosum" },
    //   { "itemValue": "Amoniacum gummi" },
    //   { "itemValue": "Ampelopsis quinquefolia" },
    //   { "itemValue": "Anacardium orientale" },
    //   { "itemValue": "Anagallis arvensis" },
    //   { "itemValue": "Anantherum muricatum" },
    //   { "itemValue": "Anemopsis californica" },
    //   { "itemValue": "Angustura vera" },
    //   { "itemValue": "Anhalonium lewinii" },
    //   { "itemValue": "Anilinum" },
    //   { "itemValue": "Anisum stellatum" },
    //   { "itemValue": "Antimonium arsenicosum" },
    //   { "itemValue": "Antimonium crudum" },
    //   { "itemValue": "Antimonium sulphuratum auratum" },
    //   { "itemValue": "Antimonium tartaricum" },
    //   { "itemValue": "Anthemis nobilis" },
    //   { "itemValue": "Anthracinum" },
    //   { "itemValue": "Anthracokali" },
    //   { "itemValue": "Antipyrinum" },
    //   { "itemValue": "Apium graveolens" },
    //   { "itemValue": "Aphis chenopodii glauci" },
    //   { "itemValue": "Apis mellifica regina" },
    //   { "itemValue": "Apocynum cannabinum" },
    //   { "itemValue": "Apocynum androsaemifolium" },
    //   { "itemValue": "Apomorphinum" },
    //   { "itemValue": "Aquilegia vulgaris" },
    //   { "itemValue": "Aragallus lamberti" },
    //   { "itemValue": "Aralia racemosa" },
    //   { "itemValue": "Aranea diadema" },
    //   { "itemValue": "Arbutus andrachne" },
    //   { "itemValue": "Areca catechu" },
    //   { "itemValue": "Argentum metallicum" },
    //   { "itemValue": "Argentum nitricum" },
    //   { "itemValue": "Argemone mexicana" },
    //   { "itemValue": "Aristolochia milhomens" },
    //   { "itemValue": "Arnica montana" },
    //   { "itemValue": "Arsenicum album" },
    //   { "itemValue": "Arsenicum bromatum" },
    //   { "itemValue": "Arsenicum hydrogenisatum" },
    //   { "itemValue": "Arsenicum metallicum" },
    //   { "itemValue": "Arsenicum iodatum" },
    //   { "itemValue": "Arsenicum sulphuratum flavum" },
    //   { "itemValue": "Artemisia vulgaris" },
    //   { "itemValue": "Arum dracontium" },
    //   { "itemValue": "Arum triphyllum" },
    //   { "itemValue": "Arundo mauritanica" },
    //   { "itemValue": "Asa foetida" },
    //   { "itemValue": "Asarum europaeum" },
    //   { "itemValue": "Asclepias cornuti" },
    //   { "itemValue": "Asclepias tuberosa" },
    //   { "itemValue": "Asimina triloba/uvaria triloba" },
    //   { "itemValue": "Asparagus officinalis" },
    //   { "itemValue": "Astacus fluviatilis" },
    //   { "itemValue": "Asterias rubens" },
    //   { "itemValue": "Astragalus mollissimus" },
    //   { "itemValue": "Aurum metallicum" },
    //   { "itemValue": "Aurum muriaticum natronatum" },
    //   { "itemValue": "Avena sativa" },
    //   { "itemValue": "Azadirachta indica" },
    //   { "itemValue": "Bacillinum burnett" },
    //   { "itemValue": "Badiaga" },
    //   { "itemValue": "Balsamum peruvianum" },
    //   { "itemValue": "Baptisia tinctoria" },
    //   { "itemValue": "Baryta acetica" },
    //   { "itemValue": "Baryta carbonica" },
    //   { "itemValue": "Baryta iodata" },
    //   { "itemValue": "Baryta muriatica" },
    //   { "itemValue": "Barosma crenulatum" },
    //   { "itemValue": "Belladonna" },
    //   { "itemValue": "Bellis perennis" },
    //   { "itemValue": "Benzoicum acidum" },
    //   { "itemValue": "Benzolum" },
    //   { "itemValue": "Berberis vulgaris" },
    //   { "itemValue": "Berberis aquifolium" },
    //   { "itemValue": "Beta vulgaris" },
    //   { "itemValue": "Bismuthum subnitricum" },
    //   { "itemValue": "Blatta americana" },
    //   { "itemValue": "Blatta orientalis" },
    //   { "itemValue": "Boletus laricis" },
    //   { "itemValue": "Boricum acidum" },
    //   { "itemValue": "Borax veneta" },
    //   { "itemValue": "Bothrops lanceolatus" },
    //   { "itemValue": "Botulinum" },
    //   { "itemValue": "Bovista lycoperdon" },
    //   { "itemValue": "Brachyglottis repens" },
    //   { "itemValue": "Bromium" },
    //   { "itemValue": "Bryonia alba" },
    //   { "itemValue": "Bufo rana" },
    //   { "itemValue": "Butyricum acidum" },
    //   { "itemValue": "Cactus grandiflorus" },
    //   { "itemValue": "Cadmium sulphuratum" },
    //   { "itemValue": "Cainca" },
    //   { "itemValue": "Cajuputum" },
    //   { "itemValue": "Caladium seguinum" },
    //   { "itemValue": "Calcarea carbonica" },
    //   { "itemValue": "Calcarea acetica" },
    //   { "itemValue": "Calcarea arsenicosa" },
    //   { "itemValue": "Calcarea fluorica" },
    //   { "itemValue": "Calcarea iodata" },
    //   { "itemValue": "Calcarea phosphorica" },
    //   { "itemValue": "Calcarea sulphurica" },
    //   { "itemValue": "Calcarea silicata" },
    //   { "itemValue": "Calendula officinalis" },
    //   { "itemValue": "Calotropis gigantea" },
    //   { "itemValue": "Caltha palustris" },
    //   { "itemValue": "Camphora" },
    //   { "itemValue": "Camphora bromata" },
    //   { "itemValue": "Canchalagua" },
    //   { "itemValue": "Cannabis indica" },
    //   { "itemValue": "Cannabis sativa" },
    //   { "itemValue": "Cantharis vesicatoria" },
    //   { "itemValue": "Capsicum annuum" },
    //   { "itemValue": "Carbolicum acidum" },
    //   { "itemValue": "Carbo animalis" },
    //   { "itemValue": "Carbo vegetabilis" },
    //   { "itemValue": "Carboneum hydrogenisatum" },
    //   { "itemValue": "Carboneum oxygenisatum" },
    //   { "itemValue": "Carboneum sulphuratum" },
    //   { "itemValue": "Carcinosinum" },
    //   { "itemValue": "Carduus marianus" },
    //   { "itemValue": "Carlsbad aqua" },
    //   { "itemValue": "Cascara sagrada" },
    //   { "itemValue": "Cascarilla" },
    //   { "itemValue": "Castoreum canadense" },
    //   { "itemValue": "Castanea vesca" },
    //   { "itemValue": "Castor equi" },
    //   { "itemValue": "Cataria nepeta" },
    //   { "itemValue": "Caulophyllum thalictroides" },
    //   { "itemValue": "Causticum" },
    //   { "itemValue": "Ceanothus americanus" },
    //   { "itemValue": "Cedron" },
    //   { "itemValue": "Cenchris contortrix" },
    //   { "itemValue": "Cerium oxalicum" },
    //   { "itemValue": "Cereus bonplandii" },
    //   { "itemValue": "Chamomilla" },
    //   { "itemValue": "Chaparro amargoso" },
    //   { "itemValue": "Chelidonium majus" },
    //   { "itemValue": "Chelone glabra" },
    //   { "itemValue": "Chenopodium anthelminticum" },
    //   { "itemValue": "Chimaphila umbellata" },
    //   { "itemValue": "China officinalis" },
    //   { "itemValue": "Chininum arsenicosum" },
    //   { "itemValue": "Chininum sulphuricum" },
    //   { "itemValue": "Chionanthus virginica" },
    //   { "itemValue": "Chloroformium" },
    //   { "itemValue": "Chloralum hydratum" },
    //   { "itemValue": "Chlorum" },
    //   { "itemValue": "Cholesterinum" },
    //   { "itemValue": "Chromicum acidum" },
    //   { "itemValue": "Chrysarobinum" },
    //   { "itemValue": "Cicuta virosa" },
    //   { "itemValue": "Cimicifuga racemosa" },
    //   { "itemValue": "Cimex lectularius" },
    //   { "itemValue": "Cina maritima" },
    //   { "itemValue": "Cineraria maritima" },
    //   { "itemValue": "Cinnabaris" },
    //   { "itemValue": "Cinnamomum ceylanicum" },
    //   { "itemValue": "Cistus canadensis" },
    //   { "itemValue": "Citrus vulgaris" },
    //   { "itemValue": "Clematis erecta" },
    //   { "itemValue": "Cobaltum metallicum" },
    //   { "itemValue": "Coccus cacti" },
    //   { "itemValue": "Coca — erythroxylon coca" },
    //   { "itemValue": "Cocainum hydrochloricum" },
    //   { "itemValue": "Cocculus indicus" },
    //   { "itemValue": "Coccinella septempunctata" },
    //   { "itemValue": "Cochlearia armoracia" },
    //   { "itemValue": "Codeinum" },
    //   { "itemValue": "Coffea cruda" },
    //   { "itemValue": "Colchicum autumnale" },
    //   { "itemValue": "Collinsonia canadensis" },
    //   { "itemValue": "Colocynthis" },
    //   { "itemValue": "Comocladia dentata" },
    //   { "itemValue": "Conium maculatum" },
    //   { "itemValue": "Convallaria majalis" },
    //   { "itemValue": "Copaiva officinalis" },
    //   { "itemValue": "Corallium rubrum" },
    //   { "itemValue": "Corallorhiza odontorhiza" },
    //   { "itemValue": "Cornus circinata" },
    //   { "itemValue": "Corydalis formosa" },
    //   { "itemValue": "Cotyledon umbilicus" },
    //   { "itemValue": "Crataegus oxyacantha" },
    //   { "itemValue": "Crocus sativus" },
    //   { "itemValue": "Crotalus horridus" },
    //   { "itemValue": "Croton tiglium" },
    //   { "itemValue": "Cubeba officinalis" },
    //   { "itemValue": "Cucurbita pepo" },
    //   { "itemValue": "Cundurango" },
    //   { "itemValue": "Cuphea viscosissima" },
    //   { "itemValue": "Cuprum metallicum" },
    //   { "itemValue": "Cuprum aceticum" },
    //   { "itemValue": "Cuprum arsenicosum" },
    //   { "itemValue": "Curare" },
    //   { "itemValue": "Cyclamen europaeum" },
    //   { "itemValue": "Cypripedium pubescens" },
    //   { "itemValue": "Cytisus laburnum" },
    //   { "itemValue": "Damiana" },
    //   { "itemValue": "Daphne indica" },
    //   { "itemValue": "Digitalis purpurea" },
    //   { "itemValue": "Dioscorea villosa" },
    //   { "itemValue": "Diosma lincaris" },
    //   { "itemValue": "Diphtherinum" },
    //   { "itemValue": "Dolichos pruriens" },
    //   { "itemValue": "Doryphora decemlineata" },
    //   { "itemValue": "Drosera rotundifolia" },
    //   { "itemValue": "Duboisia myoporoides" },
    //   { "itemValue": "Dulcamara" },
    //   { "itemValue": "Echinacea angustifolia" },
    //   { "itemValue": "Elaps corallinus" },
    //   { "itemValue": "Elaterium officinarum" },
    //   { "itemValue": "Eosinum" },
    //   { "itemValue": "Epigea repens" },
    //   { "itemValue": "Epiphegus virginiana" },
    //   { "itemValue": "Equisetum hyemale" },
    //   { "itemValue": "Erechthites hieracifolia" },
    //   { "itemValue": "Erigeron canadense" },
    //   { "itemValue": "Eriodyction californicum" },
    //   { "itemValue": "Eryngium aquaticum" },
    //   { "itemValue": "Eschscholtzia californica" },
    //   { "itemValue": "Eucalyptus globulus" },
    //   { "itemValue": "Eugenia jambosa" },
    //   { "itemValue": "Euonymus atropurpurea" },
    //   { "itemValue": "Eupatorium aromaticum" },
    //   { "itemValue": "Eupatorium perfoliatum" },
    //   { "itemValue": "Eupatorium purpureum" },
    //   { "itemValue": "Euphorbium officinalum" },
    //   { "itemValue": "Euphorbia lathyris" },
    //   { "itemValue": "Euphorbia polycarpa" },
    //   { "itemValue": "Euphrasia officinalis" },
    //   { "itemValue": "Eupionum" },
    //   { "itemValue": "Fabiana imbricata" },
    //   { "itemValue": "Fagopyrum esculentum" },
    //   { "itemValue": "Fel tauri" },
    //   { "itemValue": "Ferrum metallicum" },
    //   { "itemValue": "Ferrum iodatum" },
    //   { "itemValue": "Ferrum magneticum" },
    //   { "itemValue": "Ferrum phosphoricum" },
    //   { "itemValue": "Ferrum picricum" },
    //   { "itemValue": "Ficus religiosa" },
    //   { "itemValue": "Filix mas" },
    //   { "itemValue": "Fluoricum acidum" },
    //   { "itemValue": "Formica rufa" },
    //   { "itemValue": "Formalinum" },
    //   { "itemValue": "Fragaria vesca" },
    //   { "itemValue": "Franciscea uniflora" },
    //   { "itemValue": "Fraxinus americana" },
    //   { "itemValue": "Fucus vesiculosus" },
    //   { "itemValue": "Fuchsinum" },
    //   { "itemValue": "Fuligo ligni" },
    //   { "itemValue": "Gallicum acidum" },
    //   { "itemValue": "Galanthus nivalis" },
    //   { "itemValue": "Galium aparine" },
    //   { "itemValue": "Gambogia" },
    //   { "itemValue": "Gaultheria procumbens" },
    //   { "itemValue": "Gelsemium sempervirens" },
    //   { "itemValue": "Gentiana lutea" },
    //   { "itemValue": "Geranium maculatum" },
    //   { "itemValue": "Gettysburg water" },
    //   { "itemValue": "Ginseng quinquefolium" },
    //   { "itemValue": "Glonoïum gl = glycérine ; o = oxygène ; n = azote" },
    //   { "itemValue": "Glycerinum" },
    //   { "itemValue": "Gnaphalium polycephalum" },
    //   { "itemValue": "Gossypium herbaceum" },
    //   { "itemValue": "Granatum" },
    //   { "itemValue": "Graphites" },
    //   { "itemValue": "Gratiola officinalis" },
    //   { "itemValue": "Grindelia robusta" },
    //   { "itemValue": "Guaco" },
    //   { "itemValue": "Guajacum officinale" },
    //   { "itemValue": "Guarana" },
    //   { "itemValue": "Guarea trichiloides" },
    //   { "itemValue": "Gymnocladus canadensis" },
    //   { "itemValue": "Haematoxylon campechianum" },
    //   { "itemValue": "Hamamelis virginiana" },
    //   { "itemValue": "Hecla lava" },
    //   { "itemValue": "Hedeoma pulegioides" },
    //   { "itemValue": "Helianthus annuus" },
    //   { "itemValue": "Helleborus niger" },
    //   { "itemValue": "Heloderma" },
    //   { "itemValue": "Helonias dioica" },
    //   { "itemValue": "Hepar sulphur" },
    //   { "itemValue": "Hepatica triloba" },
    //   { "itemValue": "Heracleum sphondylium" },
    //   { "itemValue": "Hippuricum acidum" },
    //   { "itemValue": "Hippomanes" },
    //   { "itemValue": "Hippozaeninum" },
    //   { "itemValue": "Homarus" },
    //   { "itemValue": "Hura brasiliensis" },
    //   { "itemValue": "Hydrastis canadensis" },
    //   { "itemValue": "Hydrocyanicum acidum" },
    //   { "itemValue": "Hydrangea arborescens" },
    //   { "itemValue": "Hydrocotyle asiatica" },
    //   { "itemValue": "Hyoscyamus niger" },
    //   { "itemValue": "Hypericum perforatum" },
    //   { "itemValue": "Iberis amara" },
    //   { "itemValue": "Ichthyolum" },
    //   { "itemValue": "Ictodes foetida" },
    //   { "itemValue": "Ignatia amara" },
    //   { "itemValue": "Ilex aquifolium" },
    //   { "itemValue": "Indium metallicum" },
    //   { "itemValue": "Indigo tinctoria" },
    //   { "itemValue": "Indolum" },
    //   { "itemValue": "Insulinum" },
    //   { "itemValue": "Inula helenium" },
    //   { "itemValue": "Iodium" },
    //   { "itemValue": "Iodoformium" },
    //   { "itemValue": "Ipecacuanha" },
    //   { "itemValue": "Iridium metallicum" },
    //   { "itemValue": "Iris versicolor" },
    //   { "itemValue": "Jaborandi" },
    //   { "itemValue": "Jacaranda caroba" },
    //   { "itemValue": "Jalapa" },
    //   { "itemValue": "Jatropha curcas" },
    //   { "itemValue": "Joanesia asoca" },
    //   { "itemValue": "Juglans cinerea" },
    //   { "itemValue": "Juglans regia" },
    //   { "itemValue": "Juncus effusus" },
    //   { "itemValue": "Juniperus communis" },
    //   { "itemValue": "Justicia adhatoda" },
    //   { "itemValue": "Kalium arsenicosum" },
    //   { "itemValue": "Kalium bichromicum" },
    //   { "itemValue": "Kalium bromatum" },
    //   { "itemValue": "Kalium carbonicum" },
    //   { "itemValue": "Kalium chloricum" },
    //   { "itemValue": "Kalium cyanatum" },
    //   { "itemValue": "Kalium iodatum" },
    //   { "itemValue": "Kalium muriaticum" },
    //   { "itemValue": "Kalium nitricum" },
    //   { "itemValue": "Kalium phosphoricum" },
    //   { "itemValue": "Kalium permanganatum" },
    //   { "itemValue": "Kalium sulphuricum" },
    //   { "itemValue": "Kalium silicicum" },
    //   { "itemValue": "Kalmia latifolia" },
    //   { "itemValue": "Kola" },
    //   { "itemValue": "Kousso" },
    //   { "itemValue": "Kreosotum" },
    //   { "itemValue": "Lacticum acidum" },
    //   { "itemValue": "Lac caninum" },
    //   { "itemValue": "Lac vaccinum defloratum" },
    //   { "itemValue": "Lachesis mutus" },
    //   { "itemValue": "Lachnanthes tinctoria" },
    //   { "itemValue": "Lactuca virosa" },
    //   { "itemValue": "Lamium album" },
    //   { "itemValue": "Lapis albus" },
    //   { "itemValue": "Lappa arctium" },
    //   { "itemValue": "Latrodectus mactans" },
    //   { "itemValue": "Lathyrus sativus (& lathyrus cicera)" },
    //   { "itemValue": "Laurocerasus" },
    //   { "itemValue": "Lecithinum" },
    //   { "itemValue": "Ledum palustre" },
    //   { "itemValue": "Lemna minor" },
    //   { "itemValue": "Lepidium bonariense" },
    //   { "itemValue": "Leptandra virginica" },
    //   { "itemValue": "Liatris spicata" },
    //   { "itemValue": "Lilium tigrinum" },
    //   { "itemValue": "Limulus cyclops" },
    //   { "itemValue": "Linaria vulgaris" },
    //   { "itemValue": "Linum usitatissimum" },
    //   { "itemValue": "Lithium carbonicum" },
    //   { "itemValue": "Lobelia inflata" },
    //   { "itemValue": "Lobelia purpurascens" },
    //   { "itemValue": "Lolium temulentum" },
    //   { "itemValue": "Lonicera xylosteum" },
    //   { "itemValue": "Lupulus humulus" },
    //   { "itemValue": "Lycopodium clavatum" },
    //   { "itemValue": "Lycopersicum esculentum" },
    //   { "itemValue": "Lycopus virginicus" },
    //   { "itemValue": "Lyssinum" },
    //   { "itemValue": "Magnesium carbonicum" },
    //   { "itemValue": "Magnesium muriaticum" },
    //   { "itemValue": "Magnesium phosphoricum" },
    //   { "itemValue": "Magnesium sulphuricum" },
    //   { "itemValue": "Magnolia grandiflora" },
    //   { "itemValue": "Malandrinum" },
    //   { "itemValue": "Mancinella" },
    //   { "itemValue": "Manganum aceticum" },
    //   { "itemValue": "Mangifera indica" },
    //   { "itemValue": "Medorrhinum" },
    //   { "itemValue": "Medusa" },
    //   { "itemValue": "Mel cum sale" },
    //   { "itemValue": "Melilotus officinalis" },
    //   { "itemValue": "Menispermum canadense" },
    //   { "itemValue": "Mentha piperita" },
    //   { "itemValue": "Mentholum" },
    //   { "itemValue": "Menyanthes trifoliata" },
    //   { "itemValue": "Mephitis putorius" },
    //   { "itemValue": "Mercurius solubilis (hahnemanni)" },
    //   { "itemValue": "Mercurius corrosivus" },
    //   { "itemValue": "Mercurius cyanatus" },
    //   { "itemValue": "Mercurius dulcis" },
    //   { "itemValue": "Mercurius iodatus flavus" },
    //   { "itemValue": "Mercurius iodatus ruber" },
    //   { "itemValue": "Mercurius sulphuricus" },
    //   { "itemValue": "hydrarg" },
    //   { "itemValue": "oxyd" },
    //   { "itemValue": "sub-sulph" },
    //   { "itemValue": "Mercurialis perennis" },
    //   { "itemValue": "Methylenum coeruleum" },
    //   { "itemValue": "Mezereum" },
    //   { "itemValue": "Micromeria douglasii" },
    //   { "itemValue": "Millefolium officinale" },
    //   { "itemValue": "Mitchella repens" },
    //   { "itemValue": "Momordica balsamica" },
    //   { "itemValue": "Morphinum" },
    //   { "itemValue": "Moschus moschiferus" },
    //   { "itemValue": "Muriaticum acidum" },
    //   { "itemValue": "Murex purpurea" },
    //   { "itemValue": "Mygale lasiodora" },
    //   { "itemValue": "Myosotis symphytifolia" },
    //   { "itemValue": "Myrica cerifera" },
    //   { "itemValue": "Myristica sebifera" },
    //   { "itemValue": "Myrtus communis" },
    //   { "itemValue": "Naja tripudians" },
    //   { "itemValue": "Naphthalinum" },
    //   { "itemValue": "Narcissus pseudonarcissus" },
    //   { "itemValue": "Natrium arsenicosum" },
    //   { "itemValue": "Natrium carbonicum" },
    //   { "itemValue": "Natrium hypochlorosum" },
    //   { "itemValue": "Natrium muriaticum" },
    //   { "itemValue": "Natrium nitricum" },
    //   { "itemValue": "Natrium phosphoricum" },
    //   { "itemValue": "Natrium sulphuricum" },
    //   { "itemValue": "Natrium salicylicum" },
    //   { "itemValue": "Niccolum metallicum" },
    //   { "itemValue": "Niccolum sulphuricum" },
    //   { "itemValue": "Nitricum acidum" },
    //   { "itemValue": "Nitromuriaticum acidum" },
    //   { "itemValue": "Nitri spiritus dulcis" },
    //   { "itemValue": "Nuphar luteum" },
    //   { "itemValue": "Nux moschata" },
    //   { "itemValue": "Nux vomica" },
    //   { "itemValue": "Nyctanthes arbor tristis" },
    //   { "itemValue": "Ocimum canum" },
    //   { "itemValue": "Oenanthe crocata" },
    //   { "itemValue": "Oleum animale aethereum" },
    //   { "itemValue": "Oleum jecoris aselli" },
    //   { "itemValue": "Oleum santali" },
    //   { "itemValue": "Oleander" },
    //   { "itemValue": "Oniscus asellus" },
    //   { "itemValue": "Onosmodium virginianum" },
    //   { "itemValue": "Opium crudum" },
    //   { "itemValue": "Operculina turpenthum" },
    //   { "itemValue": "Opuntia ficus-indica" },
    //   { "itemValue": "Oreodaphne californica" },
    //   { "itemValue": "Origanum majorana" },
    //   { "itemValue": "Ornithogalum umbellatum" },
    //   { "itemValue": "Osmium" },
    //   { "itemValue": "Ostrya virginica" },
    //   { "itemValue": "Ovininum" },
    //   { "itemValue": "Ovi gallinae pellicula" },
    //   { "itemValue": "Oxalicum acidum" },
    //   { "itemValue": "Oxydendron arboreum" },
    //   { "itemValue": "Oxytropis lamberti" },
    //   { "itemValue": "Paeonia officinalis" },
    //   { "itemValue": "Palladium metallicum" },
    //   { "itemValue": "Paris quadrifolia" },
    //   { "itemValue": "Paraffinum" },
    //   { "itemValue": "Pareira brava" },
    //   { "itemValue": "Parthenium hysterophorus" },
    //   { "itemValue": "Passiflora incarnata" },
    //   { "itemValue": "Penthorum sedoides" },
    //   { "itemValue": "Pertussinum" },
    //   { "itemValue": "Petroleum" },
    //   { "itemValue": "Petroselinum sativum" },
    //   { "itemValue": "Phosphoricum acidum" },
    //   { "itemValue": "Phaseolus nanus" },
    //   { "itemValue": "Phellandrium aquaticum" },
    //   { "itemValue": "Phosphorus" },
    //   { "itemValue": "Physostigma venenosum" },
    //   { "itemValue": "Physalis alkekengi" },
    //   { "itemValue": "Phytolacca decandra" },
    //   { "itemValue": "Picricum acidum" },
    //   { "itemValue": "Pinus silvestris" },
    //   { "itemValue": "Piper methysticum" },
    //   { "itemValue": "Piper nigrum" },
    //   { "itemValue": "Pituitaria glandula" },
    //   { "itemValue": "Pix liquida" },
    //   { "itemValue": "Plantago major" },
    //   { "itemValue": "Platinum metallicum" },
    //   { "itemValue": "Platanus occidentalis" },
    //   { "itemValue": "Plumbum metallicum" },
    //   { "itemValue": "Podophyllinum" },
    //   { "itemValue": "Polygonum hydropiperoides" },
    //   { "itemValue": "Polyporus pinicola" },
    //   { "itemValue": "Populus tremuloides" },
    //   { "itemValue": "Populus candicans" },
    //   { "itemValue": "Primula obconica" },
    //   { "itemValue": "Primula veris" },
    //   { "itemValue": "Propylaminum" },
    //   { "itemValue": "Prunus spinosa" },
    //   { "itemValue": "Psorinum" },
    //   { "itemValue": "Ptelea trifoliata" },
    //   { "itemValue": "Pulsatilla pratensis" },
    //   { "itemValue": "Pulex irritans" },
    //   { "itemValue": "Pyrogenium" },
    //   { "itemValue": "Quassia amara" },
    //   { "itemValue": "Quebracho" },
    //   { "itemValue": "Quercus e glandibus" },
    //   { "itemValue": "Quillaya saponaria" },
    //   { "itemValue": "Radium bromatum" },
    //   { "itemValue": "Ranunculus bulbosus" },
    //   { "itemValue": "Ranunculus sceleratus" },
    //   { "itemValue": "Raphanus sativus" },
    //   { "itemValue": "Ratanhia peruviana" },
    //   { "itemValue": "Rhamnus californica" },
    //   { "itemValue": "Rheum palmatum" },
    //   { "itemValue": "Rhododendron ferrugineum" },
    //   { "itemValue": "Rhodium metallicum" },
    //   { "itemValue": "Rhus aromatica" },
    //   { "itemValue": "Rhus glabra" },
    //   { "itemValue": "Rhus toxicodendron" },
    //   { "itemValue": "Rhus venenata" },
    //   { "itemValue": "Ricinus communis" },
    //   { "itemValue": "Robinia pseudacacia" },
    //   { "itemValue": "Rosa damascena" },
    //   { "itemValue": "Rumex crispus" },
    //   { "itemValue": "Ruta graveolens" },
    //   { "itemValue": "Sabadilla" },
    //   { "itemValue": "Sabal serrulata" },
    //   { "itemValue": "Sabina" },
    //   { "itemValue": "Saccharum officinale" },
    //   { "itemValue": "Salicylicum acidum" },
    //   { "itemValue": "Salix nigra" },
    //   { "itemValue": "Salvia officinalis" },
    //   { "itemValue": "Sambucus nigra" },
    //   { "itemValue": "Sanguinaria canadensis" },
    //   { "itemValue": "Sanguinarinum nitricum" },
    //   { "itemValue": "Sanicula aqua" },
    //   { "itemValue": "Santoninum" },
    //   { "itemValue": "Saponaria officinalis" },
    //   { "itemValue": "Sarcolacticum acidum" },
    //   { "itemValue": "Sarothamnus scoparius" },
    //   { "itemValue": "Sarracenia purpurea" },
    //   { "itemValue": "Sarsaparilla officinalis" },
    //   { "itemValue": "Scrophularia nodosa" },
    //   { "itemValue": "Scutellaria laterifolia" },
    //   { "itemValue": "Secale cornutum" },
    //   { "itemValue": "Sedum acre" },
    //   { "itemValue": "Selenium metallicum" },
    //   { "itemValue": "Sempervivum tectorum" },
    //   { "itemValue": "Senecio aureus" },
    //   { "itemValue": "Senega" },
    //   { "itemValue": "Senna" },
    //   { "itemValue": "Sepia officinalis" },
    //   { "itemValue": "Serum anguillae" },
    //   { "itemValue": "Silicea terra" },
    //   { "itemValue": "Silphium lacinatum" },
    //   { "itemValue": "Sinapis nigra" },
    //   { "itemValue": "Skatolum" },
    //   { "itemValue": "Skookum chuck aqua" },
    //   { "itemValue": "Solanum nigrum" },
    //   { "itemValue": "Solidago virgaurea" },
    //   { "itemValue": "Spigelia anthelmia" },
    //   { "itemValue": "Spiranthes autumnalis" },
    //   { "itemValue": "Spiraea ulmaria" },
    //   { "itemValue": "Spongia tosta" },
    //   { "itemValue": "Squilla maritima" },
    //   { "itemValue": "Stannum metallicum" },
    //   { "itemValue": "Staphysagria" },
    //   { "itemValue": "Stellaria media" },
    //   { "itemValue": "Sticta pulmonaria" },
    //   { "itemValue": "Stigmata maydis putamen" },
    //   { "itemValue": "Stillingia silvatica" },
    //   { "itemValue": "Stramonium" },
    //   { "itemValue": "Strontium carbonicum" },
    //   { "itemValue": "Strophanthus hispidus" },
    //   { "itemValue": "Strychninum purum" },
    //   { "itemValue": "Strychninum phosphoricum" },
    //   { "itemValue": "Strychnos gaultheriana" },
    //   { "itemValue": "Succinum" },
    //   { "itemValue": "Sulphuricum acidum" },
    //   { "itemValue": "Sulphur iodatum" },
    //   { "itemValue": "Sulfonalum" },
    //   { "itemValue": "Sulphurosum acidum" },
    //   { "itemValue": "Sulphur" },
    //   { "itemValue": "Sumbulus moschatus" },
    //   { "itemValue": "Symphoricarpus racemosus" },
    //   { "itemValue": "Symphytum officinale" },
    //   { "itemValue": "Syphilinum" },
    //   { "itemValue": "Syzygium jambolanum" },
    //   { "itemValue": "Tabacum" },
    //   { "itemValue": "Tanacetum vulgare" },
    //   { "itemValue": "Tannicum acidum" },
    //   { "itemValue": "Taraxacum officinale" },
    //   { "itemValue": "Tarentula hispanica" },
    //   { "itemValue": "Tarentula cubensis" },
    //   { "itemValue": "Tartaricum acidum" },
    //   { "itemValue": "Taxus baccata" },
    //   { "itemValue": "Tellurium metallicum" },
    //   { "itemValue": "Terebinthiniae oleum" },
    //   { "itemValue": "Teucrium marum verum" },
    //   { "itemValue": "Thallium metallicum" },
    //   { "itemValue": "Thea chinensis" },
    //   { "itemValue": "Theridion curassavicum" },
    //   { "itemValue": "Thiosinaminum" },
    //   { "itemValue": "Thlaspi bursa pastoris" },
    //   { "itemValue": "Thuja occidentalis" },
    //   { "itemValue": "Thymolum" },
    //   { "itemValue": "Thymus serpyllum" },
    //   { "itemValue": "Thyroïdinum" },
    //   { "itemValue": "Tilia europaea" },
    //   { "itemValue": "Titanium metallicum" },
    //   { "itemValue": "Torula cerevisiae" },
    //   { "itemValue": "Tribulus terrestris" },
    //   { "itemValue": "Trifolium pratense" },
    //   { "itemValue": "Trillium pendulum" },
    //   { "itemValue": "Trinitrotoluenum" },
    //   { "itemValue": "Triosteum perfoliatum" },
    //   { "itemValue": "Triticum repens — agropyron repens" },
    //   { "itemValue": "Trombidium muscae domesticae" },
    //   { "itemValue": "Tuberculinum" },
    //   { "itemValue": "Tussilago petasites" },
    //   { "itemValue": "Upas tiente" },
    //   { "itemValue": "Uranium nitricum" },
    //   { "itemValue": "Urea pura" },
    //   { "itemValue": "Urtica urens" },
    //   { "itemValue": "Usnea barbata" },
    //   { "itemValue": "Ustilago maydis" },
    //   { "itemValue": "Uva ursi" },
    //   { "itemValue": "Vaccininum" },
    //   { "itemValue": "Valeriana officinalis" },
    //   { "itemValue": "Vanadium metallicum" },
    //   { "itemValue": "Vanilla aromatica" },
    //   { "itemValue": "Variolinum" },
    //   { "itemValue": "Veratrum album" },
    //   { "itemValue": "Veratrum viride" },
    //   { "itemValue": "Verbascum thapsus" },
    //   { "itemValue": "Verbena urticaefolia" },
    //   { "itemValue": "Vespa crabro" },
    //   { "itemValue": "Viburnum opulus" },
    //   { "itemValue": "Vinca minor" },
    //   { "itemValue": "Viola odorata" },
    //   { "itemValue": "Viola tricolor" },
    //   { "itemValue": "Vipera berus" },
    //   { "itemValue": "Viscum album" },
    //   { "itemValue": "Wyethia helenoidesolor" },
    //   { "itemValue": "Vipera berus" },
    //   { "itemValue": "Viscum album" },
    //   { "itemValue": "X-ray" },
    //   { "itemValue": "Xanthoxylum fraxineum" },
    //   { "itemValue": "Xerophyllum" },
    //   { "itemValue": "Yohimbinum" },
    //   { "itemValue": "Yucca filamentosa" },
    //   { "itemValue": "Zincum metallicum" },
    //   { "itemValue": "Zincum valerianicum" },
    //   { "itemValue": "Zingiber officinale" },
    //   { "itemValue": "Zizia aurea" }

    // ]
  )
  console.log("item added to new collection");
  return res.status(200).json("items sent in bulk")
   
  }

